install:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - appveyor_init.cmd
environment:
  OCAMLTOP_INCLUDE_PATH: 'C:\projects\ocaml-bigstring\.opam\ocaml-system\lib\toplevel'
  OCAMLRUNPARAM: "bs=8M"
build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - opam pin --no-action --verbose stdlib-shims https://github.com/ocaml/stdlib-shims.git
  - opam install --yes --verbose --jobs=1 alcotest
  - opam exec -- dune build @install
test_script:
  - opam exec -- dune runtest
